# Generated by Django 5.1.2 on 2024-12-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_userlogin"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlogin",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
